# to create new env: conda env create --file environment.yml
# to update env: conda env update --file environment.yml --prune
name: todos-qt
channels:
- conda-forge
- defaults
dependencies:
- python>=3.10
- pip
- loguru
- pydantic
- pyqt
- hypothesis
- mypy
- pytest
#- pytest-qt
- sqlalchemy
- pyinstaller
- python-dateutil
- qtawesome
- psycopg2-binary
- sqlmodel
- pyinstaller
- pip:
  - PyQt5-stubs
  - types-python-dateutil
