[tool.poetry]
name = "todos"
version = "0.1.0"
description = "A humble todo app"
authors = ["Mark Stefanovic"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
PyQt5 = ">=5.15,<6.0"
pydantic = ">=1.8.1"
python-dotenv = "^0.16.0"
qdarkgraystyle = "^1.0.2"
loguru = ">=0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.910"
pylint = "^2.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
