# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

line-length = 120

# Ignore `E402` (import violations) in all `__init__.py` files.
[per-file-ignores]
"__init__.py" = ["F401", "F403"]
