import datetime

from src.domain import todo, weekday, todo_category, frequencies, month

__all__ = ("HOLIDAYS",)


HOLIDAYS = [
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Thanksgiving",
        frequency=frequencies.Irregular(
            month=month.Month.November,
            week_day=weekday.Weekday.Thursday,
            week_number=4,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Thanksgiving",
        frequency=frequencies.Irregular(
            month=month.Month.November,
            week_day=weekday.Weekday.Friday,
            week_number=4,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Christmas",
        frequency=frequencies.Yearly(
            month=month.Month.November,
            day=25,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Fathers Day",
        frequency=frequencies.Irregular(
            month=month.Month.June,
            week_day=weekday.Weekday.Sunday,
            week_number=3,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Mothers Day",
        frequency=frequencies.Irregular(
            month=month.Month.May,
            week_day=weekday.Weekday.Sunday,
            week_number=2,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Labor Day",
        frequency=frequencies.Irregular(
            month=month.Month.September,
            week_day=weekday.Weekday.Monday,
            week_number=1,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Martin Luther King Jr. Day",
        frequency=frequencies.Irregular(
            month=month.Month.January,
            week_day=weekday.Weekday.Monday,
            week_number=3,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="New Year's Day",
        frequency=frequencies.Yearly(
            month=month.Month.January,
            day=1,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Presidents' Day",
        frequency=frequencies.Irregular(
            month=month.Month.February,
            week_day=weekday.Weekday.Monday,
            week_number=3,
        ),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
    todo.Todo(
        todo_id=-1,
        advance_days=30,
        category=todo_category.TodoCategory.Reminder,
        date_added=datetime.date(1970, 1, 1),
        date_completed=None,
        description="Easter",
        frequency=frequencies.Easter(),
        note="",
        start_date=datetime.date(1900, 1, 1),
    ),
]
